<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentsSeeder extends Seeder
{
    public function run()
    {
        $students = [
            // Existing students (class_id 1 & 2)
            ['massar_code' => 'D166067003', 'last_name' => 'الطاهري', 'first_name' => 'مريم', 'gender' => 'female', 'birth_date' => '2010-04-07', 'class_id' => 1],
            ['massar_code' => 'E160045521', 'last_name' => 'اوطالب', 'first_name' => 'رضوان', 'gender' => 'male', 'birth_date' => '2010-11-24', 'class_id' => 1],
            ['massar_code' => 'E161022755', 'last_name' => 'خلاوي', 'first_name' => 'خديجة', 'gender' => 'female', 'birth_date' => '2010-08-10', 'class_id' => 1],
            ['massar_code' => 'E162032690', 'last_name' => 'موحند', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => '2010-07-08', 'class_id' => 1],
            ['massar_code' => 'E162057881', 'last_name' => 'احجام', 'first_name' => 'سارة', 'gender' => 'female', 'birth_date' => '2010-12-19', 'class_id' => 1],
            ['massar_code' => 'E163021792', 'last_name' => 'ابرهوض', 'first_name' => 'اية', 'gender' => 'female', 'birth_date' => '2010-07-19', 'class_id' => 1],
            ['massar_code' => 'E164021819', 'last_name' => 'اكازي', 'first_name' => 'آية', 'gender' => 'female', 'birth_date' => '2010-07-17', 'class_id' => 1],
            ['massar_code' => 'E164022724', 'last_name' => 'صديقي', 'first_name' => 'شيماء', 'gender' => 'female', 'birth_date' => '2011-01-03', 'class_id' => 1],
            ['massar_code' => 'E164045205', 'last_name' => 'امجدود', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => '2010-08-12', 'class_id' => 1],
            ['massar_code' => 'E165021845', 'last_name' => 'اشريفي', 'first_name' => 'عمران', 'gender' => 'male', 'birth_date' => '2010-08-20', 'class_id' => 1],
            ['massar_code' => 'E165057864', 'last_name' => 'بوازداي', 'first_name' => 'خديجة', 'gender' => 'female', 'birth_date' => '2010-06-12', 'class_id' => 1],
            ['massar_code' => 'E166045494', 'last_name' => 'صابر', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => '2010-03-16', 'class_id' => 1],
            ['massar_code' => 'E167039047', 'last_name' => 'أوهميش', 'first_name' => 'ادم', 'gender' => 'male', 'birth_date' => '2010-12-26', 'class_id' => 1],
            ['massar_code' => 'E168044492', 'last_name' => 'مفتاح', 'first_name' => 'سليسى', 'gender' => 'female', 'birth_date' => '2010-08-30', 'class_id' => 1],
            ['massar_code' => 'E168045424', 'last_name' => 'بوغطا', 'first_name' => 'حنان', 'gender' => 'female', 'birth_date' => '2010-07-21', 'class_id' => 1],
            ['massar_code' => 'E168049208', 'last_name' => 'الداودي', 'first_name' => 'اية', 'gender' => 'female', 'birth_date' => '2010-03-25', 'class_id' => 1],
            ['massar_code' => 'E168055654', 'last_name' => 'بدهوش', 'first_name' => 'ادم', 'gender' => 'male', 'birth_date' => '2010-07-06', 'class_id' => 1],
            ['massar_code' => 'E177000010', 'last_name' => 'اشتاوين', 'first_name' => 'ام لال', 'gender' => 'female', 'birth_date' => '2011-01-26', 'class_id' => 1],
            ['massar_code' => 'M131382347', 'last_name' => 'حكاوي', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => '2007-11-05', 'class_id' => 2],
            ['massar_code' => 'M132279506', 'last_name' => 'ازوكي', 'first_name' => 'نورة', 'gender' => 'female', 'birth_date' => '2007-02-15', 'class_id' => 2],
            ['massar_code' => 'M134409840', 'last_name' => 'اقواس', 'first_name' => 'هشام', 'gender' => 'male', 'birth_date' => '2007-11-21', 'class_id' => 2],
            ['massar_code' => 'M138410061', 'last_name' => 'مصباح', 'first_name' => 'حمزة', 'gender' => 'male', 'birth_date' => '2008-03-12', 'class_id' => 2],
            ['massar_code' => 'M151010478', 'last_name' => 'اخميين', 'first_name' => 'ملال', 'gender' => 'female', 'birth_date' => '2010-02-01', 'class_id' => 2],
            ['massar_code' => 'M151040645', 'last_name' => 'وفقي', 'first_name' => 'انس', 'gender' => 'male', 'birth_date' => '2010-09-14', 'class_id' => 2],
            ['massar_code' => 'M152010534', 'last_name' => 'احسين', 'first_name' => 'خديجة', 'gender' => 'female', 'birth_date' => '2009-02-20', 'class_id' => 2],
            ['massar_code' => 'M152010544', 'last_name' => 'الحداوي', 'first_name' => 'سعد', 'gender' => 'male', 'birth_date' => '2009-09-10', 'class_id' => 2],
            ['massar_code' => 'M152019827', 'last_name' => 'الحداوي', 'first_name' => 'إلياس', 'gender' => 'male', 'birth_date' => '2008-12-11', 'class_id' => 2],
            ['massar_code' => 'M152043761', 'last_name' => 'رضوان', 'first_name' => 'ملال', 'gender' => 'female', 'birth_date' => '2010-02-24', 'class_id' => 2],
            ['massar_code' => 'M153000529', 'last_name' => 'ايت اتو', 'first_name' => 'عبد الإله', 'gender' => 'male', 'birth_date' => '2010-01-26', 'class_id' => 2],
            ['massar_code' => 'M153043750', 'last_name' => 'حرير', 'first_name' => 'ادم', 'gender' => 'male', 'birth_date' => '2009-05-04', 'class_id' => 2],
            ['massar_code' => 'M155035310', 'last_name' => 'اسعيدي', 'first_name' => 'هبة', 'gender' => 'female', 'birth_date' => '2009-04-01', 'class_id' => 2],
            ['massar_code' => 'M155044313', 'last_name' => 'قصبي', 'first_name' => 'يونس', 'gender' => 'male', 'birth_date' => '2010-03-07', 'class_id' => 2],
            ['massar_code' => 'M156033296', 'last_name' => 'المرمضي', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => '2009-08-09', 'class_id' => 2],
            ['massar_code' => 'M158035220', 'last_name' => 'بهلولى', 'first_name' => 'يونس', 'gender' => 'male', 'birth_date' => '2009-12-10', 'class_id' => 2],

            // TCSF-2 (class_id 3)
            ['massar_code' => 'C164086815', 'last_name' => 'الزياتي', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E160050411', 'last_name' => 'و هاسي', 'first_name' => 'وليد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E161042049', 'last_name' => 'الفلاكي', 'first_name' => 'عصام', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E162041007', 'last_name' => 'سلام', 'first_name' => 'أسماء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E163021801', 'last_name' => 'زاكور', 'first_name' => 'اسامة', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E164057871', 'last_name' => 'المصمودي', 'first_name' => 'عبد العالي', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E165049224', 'last_name' => 'مسعودي', 'first_name' => 'محمد رضا', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E165057890', 'last_name' => 'درعيو', 'first_name' => 'علي', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E166022186', 'last_name' => 'ميسور', 'first_name' => 'ليلى', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E167017631', 'last_name' => 'وباري', 'first_name' => 'هبة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E167057918', 'last_name' => 'حنفي علوي', 'first_name' => 'نهاد', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E168021781', 'last_name' => 'اهناش', 'first_name' => 'فاطمة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E168045170', 'last_name' => 'الزاهي', 'first_name' => 'حفصة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E168047614', 'last_name' => 'لحميميد', 'first_name' => 'أمين', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E169021791', 'last_name' => 'اعلاتون', 'first_name' => 'منصف', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'E169049246', 'last_name' => 'أمهش', 'first_name' => 'ادم', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'F162118967', 'last_name' => 'تقبولة', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M140091864', 'last_name' => 'الخال', 'first_name' => 'كوثر', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M143089228', 'last_name' => 'العيبي', 'first_name' => 'مونة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M145089736', 'last_name' => 'تمغيت', 'first_name' => 'شيماء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M146081745', 'last_name' => 'بوساط', 'first_name' => 'عبد الكريم', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M149109474', 'last_name' => 'اطويل', 'first_name' => 'خديجة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M150016449', 'last_name' => 'اسعيدي', 'first_name' => 'عبد الغفور', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M151010524', 'last_name' => 'بوقود', 'first_name' => 'يحيى', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M152010543', 'last_name' => 'بويعزان', 'first_name' => 'هبة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M155021138', 'last_name' => 'حمزة', 'first_name' => 'توفيق', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M158016520', 'last_name' => 'الساسي', 'first_name' => 'خالد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 3],
            ['massar_code' => 'M159035839', 'last_name' => 'اوفقير', 'first_name' => 'شيماء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 3],

            // TCSF-3 (class_id 4)
            ['massar_code' => 'D168063322', 'last_name' => 'زارو', 'first_name' => 'بدر', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E160037963', 'last_name' => 'ابوساتن', 'first_name' => 'دنيا', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E161022708', 'last_name' => 'ضريف', 'first_name' => 'هبة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E161057868', 'last_name' => 'العمراني', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E162032692', 'last_name' => 'حجري', 'first_name' => 'سهام', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E162057895', 'last_name' => 'اوبلعيد', 'first_name' => 'ملال', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E163021799', 'last_name' => 'اوخييي', 'first_name' => 'ايمان', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E163021813', 'last_name' => 'بويح', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E163037942', 'last_name' => 'بن المكرود', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E163044489', 'last_name' => 'احانو', 'first_name' => 'عبد الله', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E163057889', 'last_name' => 'الوزاري', 'first_name' => 'رميساء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E164041037', 'last_name' => 'السمار', 'first_name' => 'خديجة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E164057259', 'last_name' => 'طالبي', 'first_name' => 'يوسف', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E165021846', 'last_name' => 'اطالب', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E165044533', 'last_name' => 'المكرود', 'first_name' => 'إيمان', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E165057256', 'last_name' => 'مشور', 'first_name' => 'جهاد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E165057923', 'last_name' => 'شريف', 'first_name' => 'مريم', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E168021773', 'last_name' => 'طوعاش', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E168049229', 'last_name' => 'بداح', 'first_name' => 'آسية', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E168057263', 'last_name' => 'بن ايكو', 'first_name' => 'زكرياء', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E169047632', 'last_name' => 'أفقير', 'first_name' => 'ملال', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E177000157', 'last_name' => 'اشباني', 'first_name' => 'شيماء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'E179000017', 'last_name' => 'بولعلام', 'first_name' => 'أميمة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M133409914', 'last_name' => 'قصبي', 'first_name' => 'محمد أمين', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M137395879', 'last_name' => 'هموشة', 'first_name' => 'مريمة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M139533002', 'last_name' => 'يوتمللين', 'first_name' => 'حفصة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M145089737', 'last_name' => 'شهيون', 'first_name' => 'اسماء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M145094046', 'last_name' => 'اسعايدي', 'first_name' => 'ياسمين', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M146089648', 'last_name' => 'هوارة', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M146089685', 'last_name' => 'بوشناوي', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M149109367', 'last_name' => 'اكساس', 'first_name' => 'حفصة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M151010485', 'last_name' => 'لكاوي', 'first_name' => 'ابتسام', 'gender' => 'female', 'birth_date' => null, 'class_id' => 4],
            ['massar_code' => 'M156035312', 'last_name' => 'طاهري', 'first_name' => 'سعاد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 4],

            // TCSF-4 (class_id 5)
            ['massar_code' => 'D141102633', 'last_name' => 'حماوي', 'first_name' => 'شيماء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'D156048805', 'last_name' => 'اشتو', 'first_name' => 'رضا', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E160022192', 'last_name' => 'الفلاكي', 'first_name' => 'بلال', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E163039039', 'last_name' => 'العتماني', 'first_name' => 'مروة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E163045178', 'last_name' => 'القدك', 'first_name' => 'بلال', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E164021833', 'last_name' => 'حجري', 'first_name' => 'اسماء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E165022735', 'last_name' => 'بنوري', 'first_name' => 'هبة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E165057865', 'last_name' => 'لمعرق', 'first_name' => 'سهام', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E166044544', 'last_name' => 'البعيدي', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E167055303', 'last_name' => 'أعلاف', 'first_name' => 'نسية', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E168026928', 'last_name' => 'سعدي', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E168057919', 'last_name' => 'لمضغري', 'first_name' => 'خولة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E169057909', 'last_name' => 'ايشو', 'first_name' => 'ايسية', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E175000025', 'last_name' => 'العمراوي', 'first_name' => 'خولة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'E176000029', 'last_name' => 'اعتوتو', 'first_name' => 'مروة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M132259134', 'last_name' => 'اعلاوي', 'first_name' => 'أيوب', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M138265718', 'last_name' => 'بوشيار', 'first_name' => 'اسماعيل', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M140106142', 'last_name' => 'افروس', 'first_name' => 'ابتسام', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M141091148', 'last_name' => 'اوطاحة', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M141091929', 'last_name' => 'عامري', 'first_name' => 'رضوان', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M147089724', 'last_name' => 'سهلي', 'first_name' => 'ليلى', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M148121019', 'last_name' => 'اسماتة', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M149089683', 'last_name' => 'اليوسفي', 'first_name' => 'هبة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M149112684', 'last_name' => 'الطحاوي', 'first_name' => 'مروان', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M150001389', 'last_name' => 'صابر', 'first_name' => 'أنير', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M150010455', 'last_name' => 'افضيل', 'first_name' => 'نبيل', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M150016446', 'last_name' => 'اشباني', 'first_name' => 'حمزة', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M151010486', 'last_name' => 'خطيب', 'first_name' => 'مونية', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M151033371', 'last_name' => 'احلابن', 'first_name' => 'المصطفى', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M152010528', 'last_name' => 'بوقسيم', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M152019826', 'last_name' => 'أيوب', 'first_name' => 'زهور', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M153043752', 'last_name' => 'المقيد', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M154025112', 'last_name' => 'مسعودي', 'first_name' => 'احلام', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M156035229', 'last_name' => 'سماع', 'first_name' => 'صباح', 'gender' => 'female', 'birth_date' => null, 'class_id' => 5],
            ['massar_code' => 'M158044059', 'last_name' => 'أشيباني', 'first_name' => 'أسامة', 'gender' => 'male', 'birth_date' => null, 'class_id' => 5],

            // TCSF-5 (class_id 6)
            ['massar_code' => 'D156055861', 'last_name' => 'المحمدي', 'first_name' => 'سليمان', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E160044111', 'last_name' => 'الرشيد', 'first_name' => 'ماجدة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E161022709', 'last_name' => 'اسايدي', 'first_name' => 'حنية', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E162032691', 'last_name' => 'افي', 'first_name' => 'الياس', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E162044500', 'last_name' => 'روازي', 'first_name' => 'عمران', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E163016080', 'last_name' => 'تهامي', 'first_name' => 'سعاد', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E163021802', 'last_name' => 'اباينو', 'first_name' => 'لينا', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E163044080', 'last_name' => 'حرشاوي', 'first_name' => 'سعيد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E163057882', 'last_name' => 'ملوك', 'first_name' => 'ضحى', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E164013637', 'last_name' => 'الساسعي', 'first_name' => 'عبد الفتاح', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E164021832', 'last_name' => 'بومسعود', 'first_name' => 'نورة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E164034351', 'last_name' => 'وهابي', 'first_name' => 'سهام', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E164045211', 'last_name' => 'لهبيل', 'first_name' => 'بلال', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E165021840', 'last_name' => 'الساسي', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E165021920', 'last_name' => 'زوا', 'first_name' => 'يوسف', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E168021774', 'last_name' => 'الجاكي', 'first_name' => 'إيناس', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E168047651', 'last_name' => 'زين الدين', 'first_name' => 'نسرين', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'E169047633', 'last_name' => 'بطاشني', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'H164021876', 'last_name' => 'الكحيلي', 'first_name' => 'وليد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M130448141', 'last_name' => 'أمجعوب', 'first_name' => 'حمزة', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M132390067', 'last_name' => 'أرضون', 'first_name' => 'إبراهيم', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M133410169', 'last_name' => 'الرماني', 'first_name' => 'ايوب', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M133519745', 'last_name' => 'ارقاس', 'first_name' => 'الحسين', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M137388151', 'last_name' => 'مولفي', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M138258167', 'last_name' => 'قسطالي', 'first_name' => 'عماد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M142089638', 'last_name' => 'اسعايدي', 'first_name' => 'بلال', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M144094057', 'last_name' => 'احبار', 'first_name' => 'مريم', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M147089720', 'last_name' => 'اشروضي', 'first_name' => 'ابراهيم', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M152019880', 'last_name' => 'أعييين', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M153021141', 'last_name' => 'أمحدوك', 'first_name' => 'سيف الدين', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M158016508', 'last_name' => 'حدورت', 'first_name' => 'سارة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M158019838', 'last_name' => 'قساوي', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'M159016490', 'last_name' => 'العمراني', 'first_name' => 'هجر', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],
            ['massar_code' => 'R160001220', 'last_name' => 'بوبكيرة', 'first_name' => 'نورة', 'gender' => 'female', 'birth_date' => null, 'class_id' => 6],

            // TCSF-6 (class_id 7)
            ['massar_code' => 'E160045515', 'last_name' => 'اوطالب', 'first_name' => 'مروة', 'gender' => 'female', 'birth_date' => '2010-09-25', 'class_id' => 7],
            ['massar_code' => 'E160045518', 'last_name' => 'اوطالب', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => '2011-03-10', 'class_id' => 7],
            ['massar_code' => 'E160047616', 'last_name' => 'معقول', 'first_name' => 'آية', 'gender' => 'female', 'birth_date' => '2010-08-24', 'class_id' => 7],
            ['massar_code' => 'E161055613', 'last_name' => 'أوالا', 'first_name' => 'عائشة', 'gender' => 'female', 'birth_date' => '2010-05-30', 'class_id' => 7],
            ['massar_code' => 'E162032695', 'last_name' => 'حجري', 'first_name' => 'عبد الله', 'gender' => 'male', 'birth_date' => '2010-07-08', 'class_id' => 7],
            ['massar_code' => 'E162047603', 'last_name' => 'بن حقي', 'first_name' => 'حفصة', 'gender' => 'female', 'birth_date' => '2010-10-01', 'class_id' => 7],
            ['massar_code' => 'E163021810', 'last_name' => 'عالي', 'first_name' => 'مروى', 'gender' => 'female', 'birth_date' => '2011-01-02', 'class_id' => 7],
            ['massar_code' => 'E163057902', 'last_name' => 'شقيق', 'first_name' => 'فاطمة الزهراء', 'gender' => 'female', 'birth_date' => '2010-06-16', 'class_id' => 7],
            ['massar_code' => 'E164041034', 'last_name' => 'إشتاوين', 'first_name' => 'سالي', 'gender' => 'female', 'birth_date' => '2011-02-19', 'class_id' => 7],
            ['massar_code' => 'E166022187', 'last_name' => 'أهاض', 'first_name' => 'مروان', 'gender' => 'male', 'birth_date' => '2011-01-10', 'class_id' => 7],
            ['massar_code' => 'E166032859', 'last_name' => 'هرون', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => '2010-08-09', 'class_id' => 7],
            ['massar_code' => 'E167022742', 'last_name' => 'الخلاوي', 'first_name' => 'أشرف', 'gender' => 'male', 'birth_date' => '2010-10-13', 'class_id' => 7],
            ['massar_code' => 'E168049209', 'last_name' => 'اسعيدي', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => '2009-03-16', 'class_id' => 7],
            ['massar_code' => 'E168049234', 'last_name' => 'بداح', 'first_name' => 'محمد أمين', 'gender' => 'male', 'birth_date' => '2010-08-08', 'class_id' => 7],
            ['massar_code' => 'E168057899', 'last_name' => 'ناصري', 'first_name' => 'صفاء', 'gender' => 'female', 'birth_date' => '2010-07-11', 'class_id' => 7],
            ['massar_code' => 'E169044538', 'last_name' => 'امني', 'first_name' => 'هاجر', 'gender' => 'female', 'birth_date' => '2011-02-10', 'class_id' => 7],
            ['massar_code' => 'L156007429', 'last_name' => 'إيجوب', 'first_name' => 'آسية', 'gender' => 'female', 'birth_date' => '2010-02-01', 'class_id' => 7],
            ['massar_code' => 'M135265284', 'last_name' => 'بوبميزان', 'first_name' => 'أيوب', 'gender' => 'male', 'birth_date' => '2007-01-01', 'class_id' => 7],
            ['massar_code' => 'M135410111', 'last_name' => 'اباجي', 'first_name' => 'الياس', 'gender' => 'male', 'birth_date' => '2007-12-12', 'class_id' => 7],
            ['massar_code' => 'M136532990', 'last_name' => 'اهاض', 'first_name' => 'سالي', 'gender' => 'female', 'birth_date' => '2007-09-24', 'class_id' => 7],
            ['massar_code' => 'M137385841', 'last_name' => 'زيان', 'first_name' => 'انتصار', 'gender' => 'female', 'birth_date' => '2007-07-28', 'class_id' => 7],
            ['massar_code' => 'M137396493', 'last_name' => 'اعروش', 'first_name' => 'محمد', 'gender' => 'male', 'birth_date' => '2007-08-31', 'class_id' => 7],
            ['massar_code' => 'M146089689', 'last_name' => 'اسحاق', 'first_name' => 'نادية', 'gender' => 'female', 'birth_date' => '2008-09-25', 'class_id' => 7],
            ['massar_code' => 'M148118842', 'last_name' => 'غربي', 'first_name' => 'حسن', 'gender' => 'male', 'birth_date' => '2008-08-07', 'class_id' => 7],
            ['massar_code' => 'M150010461', 'last_name' => 'أزكو', 'first_name' => 'رحاب', 'gender' => 'female', 'birth_date' => '2009-09-08', 'class_id' => 7],
            ['massar_code' => 'M150016441', 'last_name' => 'الريشي', 'first_name' => 'صفاء', 'gender' => 'female', 'birth_date' => '2009-08-02', 'class_id' => 7],
            ['massar_code' => 'M150016444', 'last_name' => 'احيشان', 'first_name' => 'زهر', 'gender' => 'female', 'birth_date' => '2009-04-25', 'class_id' => 7],
            ['massar_code' => 'M152019879', 'last_name' => 'خطوطو', 'first_name' => 'سارة', 'gender' => 'female', 'birth_date' => '2009-07-25', 'class_id' => 7],
            ['massar_code' => 'M154035379', 'last_name' => 'وعلا', 'first_name' => 'سعيدة', 'gender' => 'female', 'birth_date' => '2009-09-03', 'class_id' => 7],
            ['massar_code' => 'M154040708', 'last_name' => 'اوفقول', 'first_name' => 'عماد', 'gender' => 'male', 'birth_date' => '2010-02-05', 'class_id' => 7],
            ['massar_code' => 'M156000453', 'last_name' => 'رزوز', 'first_name' => 'سعاد', 'gender' => 'female', 'birth_date' => '2007-04-19', 'class_id' => 7],
            ['massar_code' => 'M159042953', 'last_name' => 'ياكو', 'first_name' => 'شيماء', 'gender' => 'female', 'birth_date' => '2010-03-14', 'class_id' => 7],
        ];

        foreach ($students as $student) {
            Student::updateOrCreate(
                ['massar_code' => $student['massar_code']],
                $student
            );
        }

        $this->command->info('✅ تم إضافة جميع التلاميذ بنجاح! (' . count($students) . ' تلميذ)');
    }
}
